compute_environment: LOCAL_MACHINE
debug: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 2
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
deepspeed_config:
  deepspeed_config_file: /storage5/multimodal/work/yamaguchi/LLaVA-JP/configs/deepspeed/zero2_multi_node.json
  deepspeed_hostfile: /storage5/multimodal/work/yamaguchi/LLaVA-JP/configs/hostfiles/hostfile
  zero3_init_flag: true
main_process_port: 29515
