wandb:
  log: True
  entity: "morikoromori"
  project: "heron-leaderboard_0803"
  run_name: 'team-hatakeyama-phase2/Tanuki-8B-vision-v1_curation-gpt4o-other_gpu'
  launch: false

# basic information
testmode: false
torch_dtype: "bf16" # {fp16, bf16, fp32}
# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "mistral", "amazon_bedrock"
api: false
model_artifact: null
processor_artifact: null
tokenizer_artifact: null

model:
  _target_: null
  pretrained_model_name_or_path: 'team-hatakeyama-phase2/Tanuki-8B-vision-v1_curation'
  torch_dtype: "bfloat16"
  ignore_mismatched_sizes: true

processor:
  _target_: null
  pretrained_model_name_or_path: null
  
tokenizer:
  _target_: null
  pretrained_model_name_or_path: null

datasets:
  llava_bench_in_the_wild_artifact_path: 'vision-language-leaderboard/heron-leaderboard/llava-bench-in-the-wild:v0'
  llava_bench_in_the_wild_reference_path: 'vision-language-leaderboard/heron-leaderboard/llava-bench-in-the-wild-reference:v0'
  japanese_heron_bench_artifact_path: 'vision-language-leaderboard/heron-leaderboard/japanese-heron-bench:v0'
  japanese_heron_bench_reference_path: 'vision-language-leaderboard/heron-leaderboard/heron-bench-reference:v0'

generation:
  args:
    max_length: 500
    do_sample: true
    temperature: 0.2
    top_p: 1.0
    no_repeat_ngram_size: 3
