compute_environment: LOCAL_MACHINE
debug: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
main_training_function: main
mixed_precision: bf16
num_machines: 16
num_processes: 128
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  zero_stage: 3
  offload_optimizer_device: cpu
  offload_param_device: null
  zero3_init_flag: true
  zero3_save_16bit_model: true
  